main: de.simonsator.disablefriendlyfire.DFFMain
name: DisableFriendlyFire
version: ${project.version}
author: Simonsator
depend: [ FriendsAPIForPartyAndFriends ]
depends: [ FriendsAPIForPartyAndFriends ]
api-version: 1.13